# Generated by Django 3.1.4 on 2021-01-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sample', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'kategória',
                'verbose_name_plural': 'kategórie',
            },
        ),
        migrations.CreateModel(
            name='SimpleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontag'),
        ),
    ]
