# Generated by Django 3.1.4 on 2021-01-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210116_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplequestion',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
