# Generated by Django 3.1.4 on 2021-01-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210116_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='start_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
